### ISSUE TITLE
Troubleshooting: manual compiling MCmatlab_CUDA.c

### ISSUE THREAD

**Issue by ProjectEli** [ankrh/MCmatlab#38]
I just run Example 16 CUDAAcceleration.m of MCmatlab version 4.4.10 and got invalid MEX file error:

`CMatlab\MCmatlab-4.4.10\MCmatlab-Release\+MCmatlab\@model\private\MCmatlab_CUDA.mexw64: cannot find module`

but in the directory CUDA.mexw64 file already exists.. I think it is corrputed because if I replace it from version 4.4.9 then it says another error:

`GPUassert: an illegal memory access was encountered C:/Users/Anders/Documents/MCmatlab/+MCmatlab/src/MCmatlab_CUDA.cu 678`

It is caused by some hard coded path in 4.4.9 CUDA mexw64 file, and maybe 4.4.10 is corrupted or invalid to be read.

So I tried to compile it manually. I followed instruction written in src/MCmatlab.c using mexcuda

- Already installed VS 2022 with desktop development with cpp
- Upgraded NVIDIA CUDA toolkit 12.6 to 13.0 and doubled checked version using `nvcc --version` command
- typed gpuDevice() on MATLAB 2025b and got correct name of `NVIDIA GeForce RTX 4070 Ti SUPER`
- finally typed command on MATLAB console

`copyfile ./+MCmatlab/src/MCmatlab.c ./+MCmatlab/src/MCmatlab_CUDA.cu; mexcuda -llibut COMPFLAGS='-use_fast_math -res-usage $COMPFLAGS' -outdir +MCmatlab\@model\private .\+MCmatlab\src\MCmatlab_CUDA.cu`

Then got some compiler support compatibility error so added `-allow-unsupported-compiler`

Then got following error:

`somepath\MCmatlab-4.4.10\MCmatlab-Release\+MCmatlab\src\MCmatlablib.c(726): warning #221-D: floating-point value does not fit in
required floating-point type
    for(idx=0;idx<3;idx++) P->D[idx] = P->u[idx]? (floorf(P->i[idx]) + (P->u[idx]>0) - P->i[idx])*G->d[idx]/P->u[idx] : (float)(1e+300);`

I found that INFINITY is replaced to `1e+300` and I suspect it's cuased by unsafe type conversion from big number to small upper limit float. Then I added `#include<math.h>` in`MCmatlab.c` and in`MCmatlablib.c` and replaced INFINITY to `HUGE_VALF` and retried compile. Then following error:

`sompath\MCmatlab-4.4.10\MCmatlab-Release\+MCmatlab\src\MCmatlablib.c(1078): warning #221-D: floating-point value does not fit in
required floating-point type
            P->D[0] = P->u[0]? (floorf(P->i[0]) + (P->u[0]>0) - P->i[0])*G->d[0]/P->u[0]: ((float)((float)(1e+300)));`

Then I suspect it is due to the `-use_fast_math` option for mexcuda compile flag and removed it. Final command reads:

`copyfile ./+MCmatlab/src/MCmatlab.c ./+MCmatlab/src/MCmatlab_CUDA.cu; mexcuda -llibut COMPFLAGS=' -allow-unsupported-compiler -res-usage $COMPFLAGS' -outdir +MCmatlab\@model\private .\+MCmatlab\src\MCmatlab_CUDA.cu`

but also got same `((float)((float)(1e+300)));` error.

Now, I got lost.... I just wanted GPU acceleration to get 1000x simulation speed. How can I fix this issue? Please help.

**Comment by ankrh** [comment]
Thanks for your interest!

I don't have a definitive answer for you because I don't have access to a GPU as recent as yours so I'm not able to test. But it should be possible to get it to compile.

Version 4.4.10 runs on my PC but that doesn't help you much.

If I were you I might first look into why it says that the compiler is unsupported. Maybe there is some way to use a supported compiler.

I would not think that the -use_fast_math is the culprit but who knows.

I think you have the right idea to replace INFINITY with another expression that does fit in a single-precision float and I'm surprised that HUGE_VALF didn't solve the problem. Make sure you substitute it in all the different places that have INFINITY (I count seven places in MCmatlablib.c and one in MCmatlab.c, but I don't think you need to change the one in MCmatlab.c).

If you haven't already, you should also try asking AI for help, it might be able to spot something or know what might have changed in the CUDA compiler, or in mexcuda that would break this functionality.

Good luck, and let me know if you succeed!

**Comment by ProjectEli** [comment]
Status update:
I've been trying various approaches to resolve the `mexcuda` compilation erro, including using LLMs for assistance (Gemini 2.5pro, Claude Sonnet 4, GPT5 mini in VS2022), but I am still unsuccessful

My suspicion is that the error originates somewhere in MATLAB's core mex files, possibly related to a duplicate delclaration of `float infinity`.

With every modification I've tested, the CPU compilation (`mex`) is generally successful, but GPU compilation (`mexcuda`) has failed every time.

I understand the `mexcuda` linking process involves CU code, VS2022, CUDA toolkit, and MATLAB. However, I am not familiar with the `mex.h` core and unfortunately do not have the time to invesitgate all the related code. Also, I am not confident in my ability to correcly modify `MCmatlablib.c`, `mcmatlab.c` or the NVCC configuration.

You mentioned that the pre-compiled binary works well for you. Given my persistent compilation issues, could you please check if the compiled binary files (ex `.mexw64`) in the Github repo are up-to-date? My understanding (assisted by an LLM) is that my GPU should be able to run these pre-compiled files, even with a different CUDA toolkit version, due to the good backward compatilbility.

As a side question, is it possible to test the GPU compilation and the MC code natively, without the MATLAB mex wrapper? I am trying to isolate the issue and avoid the unforeseen complexities of the MATLAB core.

Thanks for your help.

**Comment by ankrh** [comment]
I verified that the binaries in the github repo are up to date.

For you, I've made source code files in which I've substituted all the INFINITY's in the code with 1e38, which should be a number sufficiently close to infinity. It compiles and runs for me without problems.

Try it out. If you still have problems then it can't be because of any INFINITYs, because there aren't any:

[CodeWithoutINFINITY.zip](https://github.com/user-attachments/files/23563516/CodeWithoutINFINITY.zip)

**Comment by ankrh** [comment]
PS unfortunately it would require a huge amount of work to be able to test the code natively without using MATLAB, since all of the setting up of the problem, and the visualization is done in MATLAB.

**Comment by ProjectEli** [comment]
Thank you for your kind responses. For the compilation issue, I upgraded VS from VS2022 to new VS2026, same CUDA toolkit version 13.0.r13.0, then somehow the problem disappeared. Now I can compile CUDA code without any errors. I appreciate your efforts to make CUDA MC work in the MATLAB environment.

P.S. Results generated via MCMatlab will be featured in our upcoming paper. Best wishes for your success.

**Comment by ankrh** [comment]
Thanks! Happy to hear that it works now.
